as yet unclassified
addFavicons: aRoot
	aRoot link
		beShortcutIcon;
		url: self fileLibrary / #faviconIco.
	aRoot link
		relationship: 'apple-touch-icon';
		url: self fileLibrary / #appletouchiconPng.
	aRoot link
		relationship: 'apple-touch-icon';
		url: self fileLibrary / #appletouchicon72x72Png.
	aRoot link
		relationship: 'apple-touch-icon';
		url: self fileLibrary / #appletouchicon114x114Png