as yet unclassified
addMetaTags: anHtmlRoot
	anHtmlRoot meta charset: 'utf-8'.
	anHtmlRoot meta
		contentScriptType: 'IE=edge,chrome=1';
		responseHeaderName: 'X-UA-Compatible'.
	anHtmlRoot title: 'Frameless'.
	anHtmlRoot meta
		contentScriptType: 'width=device-width, initial-scale=1';
		name: 'viewport'.
	anHtmlRoot meta
		contentScriptType: 'Dig responsive design? Hate fluid grids? Try a Frameless grid.';
		name: 'description'