as yet unclassified
renderGrid: html
	html figure
		id: 'grid';
		with: [ 
					html div class: 'col col1'.
					html div class: 'col col2'.
					html div class: 'col col3'.
					html div class: 'col col4'.
					html div class: 'col col5'.
					html div class: 'col col6'.
					html div class: 'col col7'.
					html div class: 'col col8'.
					html div class: 'col col9'.
					html div class: 'col col10'.
					html div class: 'col col11'.
					html div class: 'col col12'.
					html div class: 'col col13'.
					html div class: 'col col14'.
					html div class: 'col col15'.
					html div class: 'col col16'.
					html div class: 'col col17'.
					html div class: 'col col18'.
					html div class: 'col col19'.
					html div class: 'col col20'.
					html div class: 'col col21'.
					html div class: 'col col22'.
					html div class: 'col col23'.
					html div class: 'col col24'.
					html div class: 'col col25'.
					html div class: 'col col26'.
					html div class: 'col col27'.
					html div class: 'col col28'.
					html div class: 'col col29'.
					html div class: 'col col30'.
					html div class: 'col col31'.
					html div class: 'col col32'.
					html div class: 'col col33'.
					html div class: 'col col34'.
					html div class: 'col col35'.
					html div class: 'col col36' ]