as yet unclassified
addMetaTags: anHtmlRoot
	anHtmlRoot meta charset: 'utf-8'.
	anHtmlRoot meta
		contentScriptType: 'IE=edge,chrome=1';
		responseHeaderName: 'X-UA-Compatible'.
	anHtmlRoot title: 'Gridless demonstration'.
	anHtmlRoot meta
		contentScriptType: 'Demonstration of Gridless';
		name: 'description'.
	anHtmlRoot meta
		contentScriptType: 'width=device-width, initial-scale=1.0';
		name: 'viewport'