as yet unclassified
renderJavascriptExplanation: html
	html div
		class: 'span4';
		with: [ 
					html heading
						level: 2;
						with: 'Getting started'.
					html
						paragraph:
							'Integrating javascript with the Bootstrap library is super easy. Below we go over the basics and provide you with some awesome plugins to get you started!'.
					html
						paragraph: [ 
							html anchor
								url: 'twitter-bootstrap-javascript';
								class: 'btn primary';
								with: 'View javascript docs ¬ª' ] ]