updating
addMetaTags: anHtmlRoot
	anHtmlRoot meta charset: 'utf-8'.
	anHtmlRoot meta
		contentScriptType: 'IE=edge,chrome=1';
		responseHeaderName: 'X-UA-Compatible'.
	anHtmlRoot title: 'Gridless - An awesome HTML5 & CSS3 boilerplate for mobile first responsive, cross-browser websites'.
	anHtmlRoot meta
		contentScriptType:
				'Gridless is an optionated HTML5 and CSS3 boilerplate for making mobile first responsive, cross-browser websites with beautiful typography.';
		name: 'description'.
	anHtmlRoot meta
		contentScriptType: 'width=device-width, initial-scale=1.0';
		name: 'viewport'