as yet unclassified
renderSidebar: html
	html div
		class: 'sidebar';
		with: [ 
					html div
						class: 'well';
						with: [ 
									html heading
										level: 5;
										with: 'Sidebar'.
									html
										unorderedList: [ 
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ].
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ].
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ].
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ] ].
									html heading
										level: 5;
										with: 'Sidebar'.
									html
										unorderedList: [ 
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ].
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ].
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ].
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ].
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ].
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ] ].
									html heading
										level: 5;
										with: 'Sidebar'.
									html
										unorderedList: [ 
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ].
											html
												listItem: [ 
													html anchor
														url: '#';
														with: 'Link' ] ] ] ]