as yet unclassified
renderFormFieldSizes: html
	^ html form
		action: '';
		with: [ 
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span2';
										name: '';
										id: '';
										class: 'span2' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span3';
										name: '';
										id: '';
										class: 'span3' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span4';
										name: '';
										id: '';
										class: 'span4' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span5';
										name: '';
										id: '';
										class: 'span5' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span6';
										name: '';
										id: '';
										class: 'span6' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span7';
										name: '';
										id: '';
										class: 'span7' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span8';
										name: '';
										id: '';
										class: 'span8' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span9';
										name: '';
										id: '';
										class: 'span9' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span10';
										name: '';
										id: '';
										class: 'span10' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span11';
										name: '';
										id: '';
										class: 'span11' ].
					html div
						class: 'clearfix';
						with: [ 
									html rangeInput
										type: 'text';
										placeholder: '.span12';
										name: '';
										id: '';
										class: 'span12' ] ]