as yet unclassified
addMetaTags: anHtmlRoot
	anHtmlRoot meta charset: 'utf-8'.
	anHtmlRoot meta
		contentScriptType: 'IE=edge,chrome=1';
		responseHeaderName: 'X-UA-Compatible'.
	anHtmlRoot title: 'Try Responsive Initializr!'.
	anHtmlRoot meta
		contentScriptType: '';
		name: 'description'.
	anHtmlRoot meta
		contentScriptType: '';
		name: 'author'.
	anHtmlRoot meta
		contentScriptType: 'width=device-width,initial-scale=1';
		name: 'viewport'