rendering
renderGGSGuides: html
	html figure
		id: 'guides';
		with: [ 
					html div
						class: 'ggs-site-guide ggs-site-0';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-1';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-2';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-3';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-4';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-5';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-6';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-7';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-8';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-9';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-10';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-11';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-12';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-13';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-14';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-15';
						with: [ html div ].
					html div
						class: 'ggs-site-guide ggs-site-16';
						with: [ html div ] ]