as yet unclassified
addMetaTags: anHtmlRoot
	anHtmlRoot meta charset: 'utf-8'.
	anHtmlRoot title.
	anHtmlRoot meta
		contentScriptType: '';
		name: 'description'.
	anHtmlRoot meta
		contentScriptType: '';
		name: 'author'.
	anHtmlRoot meta
		contentScriptType: 'on';
		responseHeaderName: 'cleartype'.
	anHtmlRoot meta
		contentScriptType: 'IE=edge,chrome=1';
		responseHeaderName: 'X-UA-Compatible'.
	anHtmlRoot meta
		contentScriptType: 'width=device-width, initial-scale=1.0';
		name: 'viewport'