as yet unclassified
addMetaTags: anHtmlRoot
	anHtmlRoot meta charset: 'utf-8'.
	anHtmlRoot meta
		contentScriptType: 'IE=edge,chrome=1';
		responseHeaderName: 'X-UA-Compatible'.
	anHtmlRoot title: 'Golden Grid System'.
	anHtmlRoot meta
		contentScriptType: 'width=device-width, initial-scale=1';
		name: 'viewport'.
	anHtmlRoot meta
		contentScriptType:
				'A grid system for responsive web design. Includes folding columns, elastic gutters, a zoomable baseline grid, and a delightful grid overlay script.';
		name: 'description'