as yet unclassified
renderHiddenGuides: html
	html div
		id: 'ggs-switch';
		with: [ 
					html div class: 'ggs-switchBar'.
					html div class: 'ggs-switchBar'.
					html div class: 'ggs-switchBar' ].
	html div
		class: 'ggs-guide ggs-0';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-1';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-2';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-3';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-4';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-5';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-6';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-7';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-8';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-9';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-10';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-11';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-12';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-13';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-14';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-15';
		with: [ html div ].
	html div
		class: 'ggs-guide ggs-16';
		with: [ html div ].
	html div id: 'ggs-baseline-container'