as yet unclassified
renderHiddenTwipsyDivs: html
	html div
		class: 'twipsy fade above in';
		style: 'top: 16702.5px; left: 722.5px; display: block;';
		with: [ 
					html div class: 'twipsy-arrow'.
					html div
						class: 'twipsy-inner';
						with: 'above' ].
	html div
		class: 'twipsy fade left in';
		style: 'top: 16712px; left: 936.5px; display: block;';
		with: [ 
					html div class: 'twipsy-arrow'.
					html div
						class: 'twipsy-inner';
						with: 'left' ].
	html div
		class: 'twipsy fade right in';
		style: 'top: 16694px; left: 560.5px; display: block;';
		with: [ 
					html div class: 'twipsy-arrow'.
					html div
						class: 'twipsy-inner';
						with: 'right' ].
	html div
		class: 'twipsy fade below in';
		style: 'top: 16685.5px; left: 625px; display: block;';
		with: [ 
					html div class: 'twipsy-arrow'.
					html div
						class: 'twipsy-inner';
						with: 'below' ]