head-elements
addFavicons: aRoot
	aRoot link
		beShortcutIcon;
		url: SkeletonFileLibrary / #faviconIco.
	aRoot link
		relationship: 'apple-touch-icon';
		url: SkeletonFileLibrary / #appletouchiconPng.
	aRoot link
		relationship: 'apple-touch-icon';
		url: SkeletonFileLibrary / #appletouchicon72x72Png.
	aRoot link
		relationship: 'apple-touch-icon';
		url: SkeletonFileLibrary / #appletouchicon114x114Png