head-elements
addMetaTags: anHtmlRoot
	anHtmlRoot meta charset: 'utf-8'.
	anHtmlRoot title: 'Skeleton: Beautiful Boilerplate for Responsive, Mobile-Friendly Development'.
	anHtmlRoot meta
		contentScriptType: 'Skeleton: Beautiful Boilerplate for Responsive, Mobile-Friendly Development';
		name: 'description'.
	anHtmlRoot meta
		contentScriptType: 'Dave Gamache, hi@getskeleton.com';
		name: 'author'.
	anHtmlRoot meta
		name: 'viewport';
		content: 'width=device-width, initial-scale=1, maximum-scale=1'.
	anHtmlRoot title: 'Example Skeleton Styles'